nn_optimizer:
  epochs: 10
  batch_size: 32
  shuffle: true
  optimizer: adam
  learning_rate: 0.01
  loss: binary_crossentropy

nn_model:
  embedding_dim: 100
  hidden_dim: 128
  num_layers: 2

# torch:
#   device: 'cpu'
#   seed: 0

# data_path:
#   train: 'data/train.json'
#   valid: 'data/dev.json'
#   test : 'data/test.json'


# nn_optimizer:
#   optimizer_class: Adam  # Adam, AdamW, SGD
#   params:
#     lr: 0.001

# train:
#   epochs: 5
#   batch_size: 64
#   shuffle: True
#   loss: binary_crossentropy
